name: "Build"

on:
  push:
    branches:
      - main

env:
  NETCORE_VERSION: '8.0'                    # set this to the .NET Core version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build 

    - name: Test app
      run: dotnet test --no-build
