name: Build and test 

on: 
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  
  Build:
    runs-on: windows-latest
    steps:
      - name: Build
        working-directory: C:\FHICT\S6\Individual\U2\Services\U2API
        run: dotnet build 

