name: "Build"

on:
  push:
    branches:
      - main

env:
  NETCORE_VERSION: '8.0'                   

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: Build gateway
          working-directory: ./Services/APIGateway
          run: dotnet build 

        - name: Build user service
          working-directory: ./Services/UserService
          run: dotnet build 

        - name: Build video service
          working-directory: ./Services/VideoService
          run: dotnet build 

        - name: Build client
          working-directory: ./u2-client
          run: | 
            npm ci
            npm run build
            
        - name: Test app
          working-directory: ./Services/UnitTests
          run: dotnet test --no-build
