name: "Build"

on:
  push:
    branches:
      - main

env:
  NETCORE_VERSION: '8.0'                   

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app
      run: dotnet build 

    - name: Test app
      run: dotnet test --no-build
