name: CI

on:
  push:
    branches:
      - main

env:
  NETCORE_VERSION: '8.0'  
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./Services/UserService/Dockerfile
            image: ghcr.io/Peter0202/U2-user-service
            working-directory: ./Services/UserService
            service-name: UserService
            
          - dockerfile: ./Services/VideoService/Dockerfile
            image: ghcr.io/Peter0202/U2-video-service
            working-directory: ./Services/VideoService
            service-name: VideoService
            
    name: Build and push container ${{matrix.service-name}}
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{matrix.image}}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push 
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.working-directory}}
          file: ${{matrix.dockerfile}}
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
      
