name: "CodeQL Security Scan"
on: [push]

jobs:
  analyze:
    name: Analyza
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initializa CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{matrix.language}}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    
        
    
          
